import { describe, expect, it } from 'vitest';
import { resolveColumns } from '../../src/core/columns';
import { formatMarkdownDocument, formatMarkdownTemplate, markdownToHtml } from '../../src/core/export';
import type { Person } from '../fixtures';
import { people } from '../fixtures';

const columns = resolveColumns<Person>([
    { id: 'name', header: 'Name' },
    { id: 'department', header: 'Department' },
    { id: 'salary', header: 'Salary', formatValue: (value) => `$${value}` },
]);

describe('formatMarkdownTemplate as a report', () => {
    it('wraps the rows in a header and a footer, separated by blank lines', () => {
        const report = formatMarkdownTemplate({
            rows: people.slice(0, 2),
            columns,
            header: '# People\n\nEveryone matching the current query.',
            template: '- **{name}**, {department}',
            footer: '---\n\nGenerated by the grid.',
        });

        expect(report).toBe(
            [
                '# People',
                '',
                'Everyone matching the current query.',
                '',
                '- **Ada Lovelace**, Engineering',
                '- **Grace Hopper**, Engineering',
                '',
                '---',
                '',
                'Generated by the grid.',
            ].join('\n'),
        );
    });

    it('gives a header function the rows it covers, so it can count them', () => {
        const report = formatMarkdownTemplate({
            rows: people,
            columns,
            header: (rows) => `# ${rows.length} people`,
            template: '- {name}',
        });

        expect(report.startsWith('# 7 people\n\n- Ada Lovelace')).toBe(true);
    });

    it('resolves a placeholder through the column text, header and footer left as written', () => {
        const report = formatMarkdownTemplate({
            rows: people.slice(0, 1),
            columns,
            header: 'Totals for {salary}',
            template: '{name} earns {salary}',
        });

        // The header describes the document, so its braces are not a row's placeholders.
        expect(report).toBe('Totals for {salary}\n\nAda Lovelace earns $120000');
    });
});

describe('markdownToHtml', () => {
    it('renders the constructs a report is built from', () => {
        const html = markdownToHtml(
            [
                '# Title',
                '',
                'A paragraph with **bold**, *italic* and `code`.',
                '',
                '- one',
                '- two',
                '',
                '1. first',
                '2. second',
                '',
                '> a quote',
                '',
                '---',
                '',
                '| Name | Salary |',
                '| :--- | ---: |',
                '| Ada | 120000 |',
            ].join('\n'),
        );

        expect(html).toContain('<h1>Title</h1>');
        expect(html).toContain('<strong>bold</strong>');
        expect(html).toContain('<em>italic</em>');
        expect(html).toContain('<code>code</code>');
        expect(html).toContain('<ul><li>one</li><li>two</li></ul>');
        expect(html).toContain('<ol><li>first</li><li>second</li></ol>');
        expect(html).toContain('<blockquote><p>a quote</p></blockquote>');
        expect(html).toContain('<hr>');
        expect(html).toContain('<th style="text-align:right">Salary</th>');
        expect(html).toContain('<td style="text-align:right">120000</td>');
    });

    it('escapes the source before it decides what is markup', () => {
        const html = markdownToHtml('A cell said <script>alert(1)</script> and **meant it**');

        expect(html).not.toContain('<script>');
        expect(html).toContain('&lt;script&gt;');
        expect(html).toContain('<strong>meant it</strong>');
    });

    it('refuses to make a link out of a script URL', () => {
        const html = markdownToHtml('[click me](javascript:alert(1)) and [home](/people)');

        // Rendered as the text somebody wrote, never as something clickable.
        expect(html).not.toContain('href="javascript');
        expect(html).toContain('[click me](javascript:alert(1))');
        expect(html).toContain('<a href="/people">home</a>');
    });

    it('refuses other schemes that are not on the list, whatever their case', () => {
        for (const target of ['vbscript:msgbox(1)', 'data:text/html,x', ['JAVA', 'script:alert(1)'].join('')]) {
            expect(markdownToHtml(`[click](${target})`)).not.toContain('href=');
        }
    });

    it('judges the scheme with every control character and space taken out', () => {
        // Escaping and the link pattern already drop most of these before the check runs. The
        // check does not rely on that: DEL, for one, survives both, and a scheme split by it must
        // still be refused rather than let through as something the pattern could not read.
        const controls = [...Array.from({ length: 0x21 }, (_, code) => code), 0x7f];

        for (const code of controls) {
            const character = String.fromCharCode(code);
            for (const target of [`${character}javascript:alert(1)`, `java${character}script:alert(1)`]) {
                expect(markdownToHtml(`[click](${target})`), `U+${code.toString(16)}`).not.toContain('href=');
            }
        }
    });

    it('refuses HTML entity and percent-encoded script schemes', () => {
        const targets = [
            'javascript&#58;alert(1)',
            'javascript&colon;alert(1)',
            'java&#115;cript:alert(1)',
            'java&#x73;cript:alert(1)',
            'javascript%3aalert(1)',
            'java%73cript:alert(1)',
        ];

        for (const target of targets) {
            expect(markdownToHtml(`[click](${target})`), target).not.toContain('href=');
        }
    });

    it('leaves a fenced block alone, markup and all', () => {
        const html = markdownToHtml(['```ts', 'const x = **not bold**;', '```'].join('\n'));

        expect(html).toContain('<pre><code class="language-ts">const x = **not bold**;</code></pre>');
    });

    it('joins the lines of a paragraph and keeps blocks apart', () => {
        const html = markdownToHtml('one\ntwo\n\nthree');
        expect(html).toBe('<p>one two</p>\n<p>three</p>');
    });
});

describe('formatMarkdownDocument', () => {
    it('wraps the rendered report in the printable document', () => {
        const document = formatMarkdownDocument('# Monthly report\n\nAll good.', {
            title: 'Monthly report',
        });

        expect(document.startsWith('<!doctype html>')).toBe(true);
        expect(document).toContain('<title>Monthly report</title>');
        expect(document).toContain('<h1>Monthly report</h1>');
        expect(document).toContain('@page');
        expect(document).toContain('break-inside: avoid');
    });

    it('renders a report filled from the rows', () => {
        const markdown = formatMarkdownTemplate({
            rows: people.slice(0, 2),
            columns,
            header: '# Team',
            template: '## {name}\n\n- Department: {department}\n- Salary: {salary}',
            separator: '\n\n',
        });

        const document = formatMarkdownDocument(markdown, { title: 'Team' });

        expect(document).toContain('<h2>Ada Lovelace</h2>');
        expect(document).toContain('<li>Salary: $120000</li>');
        expect(document).toContain('<h2>Grace Hopper</h2>');
    });
});
